In [32]:
import cPickle as pickle
from matplotlib import pyplot as plt
import numpy as np
import cv2
import os
import caffe

blur_radius = 6

input_folder = '../cam_imgs/'

filter_out = ['median_image.jpg',
              'high_image.jpg', 
              'low_image.jpg', 
              'std_image.jpg']

image_list = os.listdir(input_folder)
image_list = filter(lambda x : ('.jpg' in x) and (x not in filter_out), image_list)

median_image = caffe.io.load_image(input_folder + 'median_image.jpg')
high_image   = caffe.io.load_image(input_folder + 'high_image.jpg')
low_image    = caffe.io.load_image(input_folder + 'low_image.jpg')
std_image    = caffe.io.load_image(input_folder + 'std_image.jpg')

image_shape = median_image.shape

print median_image.shape
print high_image.shape
print low_image.shape
print std_image.shape

(540, 960, 3)
(540, 960, 3)
(540, 960, 3)
(540, 960, 3)


In [33]:
plt.subplot(221)
plt.imshow(median_image)
plt.subplot(222)
plt.imshow(low_image)
plt.subplot(223)
plt.imshow(high_image)
plt.subplot(224)
plt.imshow(std_image)
plt.axis('off')
plt.show()

In [34]:
in_image = caffe.io.load_image(input_folder + image_list[0])
in_image = cv2.imread(input_folder + image_list[0])
blur_in_image = cv2.blur(in_image, (blur_radius, blur_radius))

In [37]:
foreground_indices = np.where((blur_in_image[-3] > high_image[-3]) and (blur_in_image[-2] > high_image[-2]) and (blur_in_image[-1] > high_image[-1])
foreground = np.zeros(image_shape)
foreground[foreground_indices] = in_image[foreground_indices]
foreground_indices = np.where((blur_in_image.mean(-1) < low_image.mean(-1)))
foreground[foreground_indices] = in_image[foreground_indices]

SyntaxError: invalid syntax (<ipython-input-37-8477bac2c15a>, line 2)

In [36]:
print foreground

plt.imshow(foreground)
plt.show()

[[[ 0.38039216  0.32156864  0.34117648]
  [ 0.49019608  0.44313726  0.45882353]
  [ 0.51764709  0.47843137  0.50980395]
  ..., 
  [ 0.0627451   0.0627451   0.0627451 ]
  [ 0.05490196  0.05490196  0.05490196]
  [ 0.05098039  0.05098039  0.05098039]]

 [[ 0.39607844  0.33725491  0.35686275]
  [ 0.47450981  0.43137255  0.44705883]
  [ 0.49803922  0.4627451   0.48235294]
  ..., 
  [ 0.07450981  0.07450981  0.07450981]
  [ 0.07058824  0.07058824  0.07058824]
  [ 0.06666667  0.06666667  0.06666667]]

 [[ 0.47843137  0.41960785  0.43137255]
  [ 0.51764709  0.47450981  0.49019608]
  [ 0.          0.          0.        ]
  ..., 
  [ 0.07843138  0.07843138  0.07843138]
  [ 0.07450981  0.07450981  0.07450981]
  [ 0.07843138  0.07843138  0.07843138]]

 ..., 
 [[ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  ..., 
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.     